triggers:
  user-message:
    input:
      USER_MESSAGE:
        type: string
      FILES:
        type: file[]
        optional: true

skills:
  crawl-urls:
    display: description

agent:
  model: openai/gpt-4o
  system: system
  temperature: 0.7
  webSearch: true
  agentic: true
  skills:
    - crawl-urls

handlers:
  user-message:
    Add user message:
      block: add-message
      role: user
      prompt: user-message
      input: [USER_MESSAGE]
      files: [FILES]
      display: hidden

    Respond:
      block: next-message
