/**
 * Regenerates current-models.txt from the models your AWS account can actually
 * invoke in BEDROCK_AWS_REGION.
 *
 * Model ids and regional availability change often, and some models cannot be
 * invoked by their base id at all (they require an inference profile), so the
 * list is generated rather than hand-maintained.
 *
 *   npm run sync:models
 */

import 'dotenv/config';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import {
  BedrockClient,
  ListFoundationModelsCommand,
  ListInferenceProfilesCommand,
} from '@aws-sdk/client-bedrock';
import { readBedrockCredentials, bedrockRegion } from '../lib/bedrock-client.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUTPUT_FILE = path.join(__dirname, '..', 'current-models.txt');

const region = bedrockRegion();
const credentials = readBedrockCredentials();
const client = new BedrockClient({ region, ...(credentials ? { credentials } : {}) });

/** Inference profile ids, which are what on-demand chat traffic should use. */
async function listInferenceProfiles() {
  const ids = [];
  let nextToken;
  do {
    const res = await client.send(new ListInferenceProfilesCommand({ nextToken }));
    for (const profile of res.inferenceProfileSummaries ?? []) {
      if (profile.status && profile.status !== 'ACTIVE') continue;
      if (profile.inferenceProfileId) ids.push(profile.inferenceProfileId);
    }
    nextToken = res.nextToken;
  } while (nextToken);
  return ids;
}

/**
 * Base model ids that support streaming text output. Kept as a fallback for
 * regions or models without an inference profile.
 */
async function listStreamingTextModels() {
  const res = await client.send(new ListFoundationModelsCommand({
    byOutputModality: 'TEXT',
    byInferenceType: 'ON_DEMAND',
  }));
  return (res.modelSummaries ?? [])
    .filter((m) => m.responseStreamingSupported)
    .map((m) => m.modelId)
    .filter(Boolean);
}

const [profiles, baseModels] = await Promise.all([
  listInferenceProfiles(),
  listStreamingTextModels(),
]);

// Prefer inference profiles; only list a base model when no profile wraps it.
const wrapped = new Set(profiles.map((id) => id.split('.').slice(1).join('.')));
const standalone = baseModels.filter((id) => !wrapped.has(id));

const lines = [
  '# Amazon Bedrock models available to this account.',
  `# Generated by \`npm run sync:models\` for region ${region}.`,
  '# Docs: https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html',
  '',
  '# Cross-region inference profiles (preferred — higher availability)',
  ...profiles.sort(),
  '',
  '# Single-region base model ids',
  ...standalone.sort(),
  '',
];

await fs.writeFile(OUTPUT_FILE, lines.join('\n'));
console.log(
  `Wrote ${profiles.length + standalone.length} models to current-models.txt (region ${region}).`,
);
